title: Stan's Blog
email: stan_wong@foxmail.com
description: >-
  Stan's blog
baseurl: ""
url: ""
# twitter_username: jekyllrb
github_username:  stanwon

# Build settings
theme: minima
plugins:
  - jekyll-feed
